#Configure the External Bluetooth speaker name to pair and connect

EXT_BT_devices="<Ext_BT_device_name>"



#Configure the required sleep duration before getting discovered device list

sleep_timer=25

#Configure the number of retries to check for EXT_BT_devices in discovered_device list

max_scan_retries=3


#Configure the retries for discovered device list after scaning

max_scan_discovered_devices=3


#Configure the Deeplink for AV playback in Youtube

yt_URL="<yt_video_url>"


#Configure the Deeplink for AV playback in Amazon Prime

amz_URL="<amz_video_url>"


#configure the gst_launch URL for AV playback in DUT

htmlApp_launch_URL="<html_launch_url>"


#Configure the TestCase Execution Resuls updating path

result_directory="/home/root/test_Execution_results"


#Configure the Issue logs moving path

issue_logs_directory="/home/root/test_Execution_results/logs"


#Configure the Max retries needed to check the reconnection of BT speaker after reboot

max_reconnect_check=5


#Configure the Volume levels and Mute Info details

default_volume_level=122
increase_volume=(152 188 224)
decrease_volume=(108 72 36)


#Configure the memcr apps to check the status 

memcr_test_apps=("YouTube" "Amazon" "YouTubeTV")


#Configure the memcr app launch type Via rdkservice API's or via generateKey method

app_launch_type="RDK_service_API"
#app_launch_type="RDK_generateKey"


#configure the app bundle names to download and install

browser_test_app_bundle="com.rdkcentral.browser_test+0.3.1.bolt"
webaudio_app_bundle="com.rdkcentral.webaudio_manual+0.3.1.bolt"
app_download_server="<app_download_server>"
installed_app_ver="<app_version>"


#configure a empty dynamic clientID variable to use inside function generateKey_inApp_navigation

dynamic_appInstanceId=""


#Configure the Opacity values for  RDKShell Tests

opacity_values=(0 75 50 25)


#Configure the HDCP COMPLIANCE related logs file path

hdcp_logs_path="/opt/logs/uimgr_log.txt" 


#Configure the App launch/install/download/terminate related logs file path

app_Operations_logs_path="/opt/logs/wpeframework.log"


#Configure the IPv6 supported SSID name to check in pre-condition

ipv6_conf_SSID=""


#Configure the https server details for log Upload

log_upload_server="<log_upload_server>"
xconf_server_url="<Xconf_instance_server_url>"
upload_server_loc="upload_server_location"


#Configure the details XCONF configuration check and Firmware upgrade 

xconf_config_check_url="https://<xconf_instance_server>/xconf/swu/stb?eStbMac="
xconf_imagefile_to_upgrade="<Firmware_file_name>"
xconf_imagefile_version="<firmware_file_version>"
xconf_reboot_immediately="true"
xconf_firmware_dwld_location="<xconf_firmware_dwld_location>"
xconf_firmwareConfig_name="<Firmware_config_name>"
xconf_API_key_token="<Senseitive_Api_token>"
xconf_restApi_firmware_config="<xconf_restApi_for_firmware_config>"
xconf_firmwareConfig_query_url="<xconf_firmware_Query_URL>"


































