# =============================================================================
# Bolt Apps Bundle Generator - Configuration File
# =============================================================================
# To get started, update BASE_URL to match your hosting environment.

#BASE_URL=https://<TM_IP>/tdkservice/fileStore/lightning-apps
BASE_URL=https://<TM_IP>/images
VERSION=0.1.0
CERT_PASSPHRASE=
WPE_VERSION=
DEV_MODE=false

[com.rdkcentral.lightning-unified-player]
displayName=RDK Lightning Unified Player
appPath=unifiedplayer
entryFile=build/index.html

[com.rdkcentral.html-player]
displayName=RDK HTML Player
entryFile=htmlplayer.html

[com.rdkcentral.animation-app]
displayName=RDK Animation App
appPath=animations
entryFile=build/index.html

[com.rdkcentral.multi-animation-app]
displayName=RDK Multi Animation App
appPath=multianimations
entryFile=build/index.html

[com.rdkcentral.object-animation-app]
displayName=RDK Object Animation App
appPath=objectanimations
entryFile=build/index.html

[com.rdkcentral.webaudio]
displayName=RDK Web Audio
appPath=webaudio
entryFile=WebAudioTestDynamic.html
webAudio=true

[com.rdkcentral.webaudioBrowser]
displayName=RDK Web Audio Browser
appPath=webaudio
entryFile=Browser_test_app.html
webAudio=true

[com.rdkcentral.webaudioManual]
displayName=RDK Web Audio Manual
appPath=webaudio
entryFile=Webaudio_test_Manual.html
webAudio=true

[com.rdkcentral.channelchange]
displayName=RDK Channel Change
entryFile=ChannelChangeTest.html?test_duration=168

[com.rdkcentral.keytest]
displayName=RDK Key Test
entryFile=KeyStressTest.html

[com.rdkcentral.google]
displayName=RDK Google
entryPoint=https://www.google.com/

[com.rdkcentral.css3]
displayName=RDK CSS3
entryPoint=https://css3test.com/

[com.rdkcentral.speedometer]
displayName=RDK Speedometer
entryPoint=https://browserbench.org/Speedometer3.1/

[com.rdkcentral.motion]
displayName=RDK Motion
entryPoint=https://browserbench.org/MotionMark1.2/

[com.rdkcentral.animation]
displayName=RDK Animation
entryPoint=https://themaninblue.com/experiment/AnimationBenchmark/canvas/

[com.rdkcentral.octane]
displayName=RDK Octane
entryPoint=https://chromium.github.io/octane/?auto=1

[com.rdkcentral.kraken]
displayName=RDK Kraken
entryPoint=https://mozilla.github.io/krakenbenchmark.mozilla.org/kraken-1.1/driver.html

[com.rdkcentral.smashcat]
displayName=RDK Smashcat
entryPoint=http://www.smashcat.org/av/canvas_test/
